// <auto-generated />
using System;
using System.Collections.Generic;
using ContentPilot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContentPilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912094702_EvalTracking")]
    partial class EvalTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentPilot.Domain.Branding.AudiencePersona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("segment");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audience_personas");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_audience_personas_brand_id");

                    b.HasIndex("TenantId", "BrandId", "IsPrimary")
                        .HasDatabaseName("ix_audience_personas_tenant_id_brand_id_is_primary");

                    b.ToTable("audience_personas", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.PrimitiveCollection<List<string>>("_languages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("languages");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_brands_tenant_id_name");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("media_type");

                    b.Property<short>("Origin")
                        .HasColumnType("smallint")
                        .HasColumnName("origin");

                    b.Property<Guid?>("ParentAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_asset_id");

                    b.Property<string>("PerceptualHash")
                        .HasColumnType("text")
                        .HasColumnName("perceptual_hash");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variant")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("variant");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.PrimitiveCollection<List<string>>("_dominantColors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("dominant_colors");

                    b.PrimitiveCollection<List<string>>("_tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_brand_assets");

                    b.HasIndex("ParentAssetId")
                        .HasDatabaseName("ix_brand_assets_parent_asset_id");

                    b.HasIndex("BrandId", "Sha256", "Variant")
                        .IsUnique()
                        .HasDatabaseName("ix_brand_assets_content");

                    b.HasIndex("TenantId", "BrandId", "Kind")
                        .HasDatabaseName("ix_brand_assets_tenant_id_brand_id_kind");

                    b.ToTable("brand_assets", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Messaging")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("messaging");

                    b.Property<string>("OperatorNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("operator_notes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Visual")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("visual");

                    b.Property<string>("Voice")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("voice");

                    b.HasKey("Id")
                        .HasName("pk_brand_profiles");

                    b.HasIndex("BrandId")
                        .IsUnique()
                        .HasDatabaseName("ix_brand_profiles_brand_id");

                    b.ToTable("brand_profiles", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandProfileVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_brand_profile_versions");

                    b.HasIndex("BrandId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_brand_profile_versions_brand_id_content_hash");

                    b.HasIndex("TenantId", "BrandId", "CreatedAt")
                        .HasDatabaseName("ix_brand_profile_versions_tenant_id_brand_id_created_at");

                    b.ToTable("brand_profile_versions", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.ContentPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<int>("CarouselsPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("carousels_per_week");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("GenerationDay")
                        .HasColumnType("smallint")
                        .HasColumnName("generation_day");

                    b.Property<TimeOnly>("GenerationTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("generation_time");

                    b.Property<int>("PostsPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("posts_per_week");

                    b.Property<int>("ReelsPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("reels_per_week");

                    b.Property<bool>("ScheduledGenerationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("scheduled_generation_enabled");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<List<string>>("_excludedTopics")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("excluded_topics");

                    b.PrimitiveCollection<List<string>>("_preferredTopics")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("preferred_topics");

                    b.PrimitiveCollection<int[]>("_publishDays")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("publish_days");

                    b.HasKey("Id")
                        .HasName("pk_content_preferences");

                    b.HasIndex("BrandId")
                        .IsUnique()
                        .HasDatabaseName("ix_content_preferences_brand_id");

                    b.HasIndex("GenerationDay")
                        .HasDatabaseName("ix_content_preferences_scheduled")
                        .HasFilter("scheduled_generation_enabled");

                    b.ToTable("content_preferences", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.IndustryProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_industry_profiles");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_industry_profiles_key");

                    b.ToTable("industry_profiles", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.ProductFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("evidence");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("key");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("statement");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_product_facts");

                    b.HasIndex("BrandId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_product_facts_brand_id_key");

                    b.ToTable("product_facts", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.ContentAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("media_type");

                    b.Property<string>("MetaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_json");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_content_assets");

                    b.HasIndex("ContentItemId", "Attempt")
                        .HasDatabaseName("ix_content_assets_content_item_id_attempt");

                    b.ToTable("content_assets", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.ContentCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("BrandProfileVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_profile_version_id");

                    b.Property<long>("BudgetMicroCents")
                        .HasColumnType("bigint")
                        .HasColumnName("budget_micro_cents");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Theme")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("theme");

                    b.Property<short>("Trigger")
                        .HasColumnType("smallint")
                        .HasColumnName("trigger");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id")
                        .HasName("pk_content_campaigns");

                    b.HasIndex("BrandId", "WeekStart")
                        .IsUnique()
                        .HasDatabaseName("ix_content_campaigns_brand_id_week_start");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_content_campaigns_tenant_id_status");

                    b.ToTable("content_campaigns", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.ContentHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<string>("Hook")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hook");

                    b.Property<long>("HookSimHash")
                        .HasColumnType("bigint")
                        .HasColumnName("hook_sim_hash");

                    b.Property<int?>("HumanRating")
                        .HasColumnType("integer")
                        .HasColumnName("human_rating");

                    b.Property<string>("Pillar")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("pillar");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<double?>("QualityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("quality_score");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("topic");

                    b.Property<long>("TopicSimHash")
                        .HasColumnType("bigint")
                        .HasColumnName("topic_sim_hash");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_content_history");

                    b.HasIndex("BrandId", "ApprovedAt")
                        .HasDatabaseName("ix_content_history_brand_id_approved_at");

                    b.ToTable("content_history", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BestAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("best_asset_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("objective");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Pillar")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("pillar");

                    b.Property<int>("PublishDay")
                        .HasColumnType("integer")
                        .HasColumnName("publish_day");

                    b.Property<int>("QualityAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("quality_attempts");

                    b.Property<string>("RepetitionRisk")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("repetition_risk");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int>("StepsExecuted")
                        .HasColumnType("integer")
                        .HasColumnName("steps_executed");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("topic");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_content_items");

                    b.HasIndex("CampaignId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_content_items_campaign_id_ordinal");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_content_items_tenant_id_status");

                    b.ToTable("content_items", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.ContentRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FindingsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("findings_json");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("RemediationAction")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("remediation_action");

                    b.Property<string>("RestartAtStep")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("restart_at_step");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_content_revisions");

                    b.HasIndex("ContentItemId", "Attempt")
                        .HasDatabaseName("ix_content_revisions_content_item_id_attempt");

                    b.ToTable("content_revisions", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.CreativeSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SpecHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("spec_hash");

                    b.Property<string>("SpecJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("spec_json");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_version_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_creative_specs");

                    b.HasIndex("TemplateVersionId")
                        .HasDatabaseName("ix_creative_specs_template_version_id");

                    b.HasIndex("ContentItemId", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("ix_creative_specs_content_item_id_attempt");

                    b.ToTable("creative_specs", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.TemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("manifest_json");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("template_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_template_versions");

                    b.HasIndex("TemplateId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_template_versions_template_id_version");

                    b.ToTable("template_versions", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Evals.EvalResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detail");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<Guid>("EvalRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("eval_run_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scenario_name");

                    b.HasKey("Id")
                        .HasName("pk_eval_results");

                    b.HasIndex("ScenarioName")
                        .HasDatabaseName("ix_eval_results_scenario_name");

                    b.HasIndex("EvalRunId", "ScenarioName")
                        .HasDatabaseName("ix_eval_results_eval_run_id_scenario_name");

                    b.ToTable("eval_results", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Evals.EvalRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Mode")
                        .HasColumnType("smallint")
                        .HasColumnName("mode");

                    b.Property<int>("PassedScenarios")
                        .HasColumnType("integer")
                        .HasColumnName("passed_scenarios");

                    b.Property<DateTimeOffset>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.Property<int>("TotalScenarios")
                        .HasColumnType("integer")
                        .HasColumnName("total_scenarios");

                    b.HasKey("Id")
                        .HasName("pk_eval_runs");

                    b.HasIndex("RunAt")
                        .HasDatabaseName("ix_eval_runs_run_at");

                    b.ToTable("eval_runs", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Observability.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("agent_name");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("agent_version");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_read_tokens");

                    b.Property<long>("CacheWriteTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_write_tokens");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<long>("CostMicroCents")
                        .HasColumnType("bigint")
                        .HasColumnName("cost_micro_cents");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("InputRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("input_ref");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model_id");

                    b.Property<short>("Outcome")
                        .HasColumnType("smallint")
                        .HasColumnName("outcome");

                    b.Property<string>("OutputRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("output_ref");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<Guid>("PromptVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_version_id");

                    b.Property<string>("SpanId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("span_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("ValidationFailure")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("validation_failure");

                    b.HasKey("Id")
                        .HasName("pk_agent_runs");

                    b.HasIndex("CampaignId", "StartedAt")
                        .HasDatabaseName("ix_agent_runs_campaign_id_started_at");

                    b.HasIndex("AgentName", "PromptVersionId", "Outcome")
                        .HasDatabaseName("ix_agent_runs_agent_name_prompt_version_id_outcome");

                    b.ToTable("agent_runs", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Observability.CostEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<long>("AmountMicroCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_micro_cents");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<DateTimeOffset>("IncurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("incurred_at");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("provider");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("resource");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("UnitPriceMicroCentsPerMillion")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price_micro_cents_per_million");

                    b.Property<long>("Units")
                        .HasColumnType("bigint")
                        .HasColumnName("units");

                    b.HasKey("Id")
                        .HasName("pk_cost_entries");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_cost_entries_campaign_id");

                    b.HasIndex("TenantId", "IncurredAt")
                        .HasDatabaseName("ix_cost_entries_tenant_id_incurred_at");

                    b.ToTable("cost_entries", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Observability.PromptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ModelProfile")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("model_profile");

                    b.Property<string>("PromptId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("prompt_id");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("SchemaName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("schema_name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_prompt_versions");

                    b.HasIndex("PromptId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_prompt_versions_prompt_id_version");

                    b.ToTable("prompt_versions", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Packaging.CampaignPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BuiltAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("built_at");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("EmailSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_sent_at");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("manifest_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ZipKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("zip_key");

                    b.HasKey("Id")
                        .HasName("pk_campaign_packages");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_packages_campaign_id");

                    b.ToTable("campaign_packages", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Packaging.HumanRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_human_ratings");

                    b.HasIndex("ContentItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_human_ratings_content_item_id");

                    b.ToTable("human_ratings", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Quality.QualityReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("findings");

                    b.Property<short>("Gate")
                        .HasColumnType("smallint")
                        .HasColumnName("gate");

                    b.Property<short>("Outcome")
                        .HasColumnType("smallint")
                        .HasColumnName("outcome");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_quality_reviews");

                    b.HasIndex("ContentItemId", "Attempt", "Gate")
                        .IsUnique()
                        .HasDatabaseName("ix_quality_reviews_content_item_id_attempt_gate");

                    b.HasIndex("TenantId", "Gate", "EvaluatedAt")
                        .HasDatabaseName("ix_quality_reviews_tenant_id_gate_evaluated_at");

                    b.ToTable("quality_reviews", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Limits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Workflow.BudgetReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<long>("EstimateMicroCents")
                        .HasColumnType("bigint")
                        .HasColumnName("estimate_micro_cents");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<DateTimeOffset>("ReservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_budget_reservations");

                    b.HasIndex("CampaignId", "ReleasedAt", "ExpiresAt")
                        .HasDatabaseName("ix_budget_reservations_campaign_id_released_at_expires_at");

                    b.HasIndex("ContentItemId", "ReleasedAt", "ExpiresAt")
                        .HasDatabaseName("ix_budget_reservations_content_item_id_released_at_expires_at");

                    b.ToTable("budget_reservations", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Workflow.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<int>("MaxQualityAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_quality_attempts");

                    b.Property<int>("MaxSchemaRepairAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_schema_repair_attempts");

                    b.Property<int>("MaxStepsExecuted")
                        .HasColumnType("integer")
                        .HasColumnName("max_steps_executed");

                    b.Property<int>("MaxTransientAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_transient_attempts");

                    b.Property<int>("QualityAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("quality_attempts");

                    b.Property<int>("SchemaRepairAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("schema_repair_attempts");

                    b.Property<short>("Scope")
                        .HasColumnType("smallint")
                        .HasColumnName("scope");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<int>("StepsExecuted")
                        .HasColumnType("integer")
                        .HasColumnName("steps_executed");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TransientAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("transient_attempts");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workflow_runs");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_workflow_runs_campaign_id");

                    b.HasIndex("Scope", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_runs_scope_entity_id")
                        .HasFilter("state = 0");

                    b.HasIndex("State", "LeaseUntil")
                        .HasDatabaseName("ix_workflow_runs_state_lease_until");

                    b.HasIndex("TenantId", "CampaignId")
                        .HasDatabaseName("ix_workflow_runs_tenant_id_campaign_id");

                    b.ToTable("workflow_runs", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Workflow.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<short>("Outcome")
                        .HasColumnType("smallint")
                        .HasColumnName("outcome");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("step_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_steps");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_steps_idempotency_key");

                    b.HasIndex("WorkflowRunId", "StartedAt")
                        .HasDatabaseName("ix_workflow_steps_workflow_run_id_started_at");

                    b.ToTable("workflow_steps", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Infrastructure.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("locked_by");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("LeaseUntil")
                        .HasDatabaseName("ix_jobs_leased")
                        .HasFilter("state = 1");

                    b.HasIndex("RunAt", "Priority")
                        .HasDatabaseName("ix_jobs_pending")
                        .HasFilter("state = 0");

                    b.HasIndex("TenantId", "Type", "State")
                        .HasDatabaseName("ix_jobs_tenant_id_type_state");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.AudiencePersona", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audience_personas_brands_brand_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.Brand", b =>
                {
                    b.HasOne("ContentPilot.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brands_tenants_tenant_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandAsset", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_assets_brands_brand_id");

                    b.HasOne("ContentPilot.Domain.Branding.BrandAsset", null)
                        .WithMany()
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_brand_assets_brand_assets_parent_asset_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandProfile", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_profiles_brands_brand_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandProfileVersion", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_profile_versions_brands_brand_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.ContentPreferences", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_preferences_brands_brand_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.ProductFact", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_facts_brands_brand_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.ContentAsset", b =>
                {
                    b.HasOne("ContentPilot.Domain.Content.ContentItem", null)
                        .WithMany()
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_assets_content_items_content_item_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.ContentCampaign", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_campaigns_brands_brand_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.ContentHistoryEntry", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_history_brands_brand_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.ContentItem", b =>
                {
                    b.HasOne("ContentPilot.Domain.Content.ContentCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_items_content_campaigns_campaign_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.ContentRevision", b =>
                {
                    b.HasOne("ContentPilot.Domain.Content.ContentItem", null)
                        .WithMany()
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_revisions_content_items_content_item_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Content.CreativeSpec", b =>
                {
                    b.HasOne("ContentPilot.Domain.Content.ContentItem", null)
                        .WithMany()
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creative_specs_content_items_content_item_id");

                    b.HasOne("ContentPilot.Domain.Content.TemplateVersion", null)
                        .WithMany()
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_creative_specs_template_versions_template_version_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Evals.EvalResult", b =>
                {
                    b.HasOne("ContentPilot.Domain.Evals.EvalRun", null)
                        .WithMany()
                        .HasForeignKey("EvalRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eval_results_eval_runs_eval_run_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Observability.AgentRun", b =>
                {
                    b.HasOne("ContentPilot.Domain.Content.ContentCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_runs_content_campaigns_campaign_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Observability.CostEntry", b =>
                {
                    b.HasOne("ContentPilot.Domain.Content.ContentCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cost_entries_content_campaigns_campaign_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Packaging.CampaignPackage", b =>
                {
                    b.HasOne("ContentPilot.Domain.Content.ContentCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_packages_content_campaigns_campaign_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Packaging.HumanRating", b =>
                {
                    b.HasOne("ContentPilot.Domain.Content.ContentItem", null)
                        .WithMany()
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_human_ratings_content_items_content_item_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Quality.QualityReview", b =>
                {
                    b.HasOne("ContentPilot.Domain.Content.ContentItem", null)
                        .WithMany()
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quality_reviews_content_items_content_item_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Workflow.BudgetReservation", b =>
                {
                    b.HasOne("ContentPilot.Domain.Content.ContentCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_reservations_content_campaigns_campaign_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Workflow.WorkflowRun", b =>
                {
                    b.HasOne("ContentPilot.Domain.Content.ContentCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_runs_content_campaigns_campaign_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Workflow.WorkflowStep", b =>
                {
                    b.HasOne("ContentPilot.Domain.Workflow.WorkflowRun", null)
                        .WithMany()
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_steps_workflow_runs_workflow_run_id");
                });
#pragma warning restore 612, 618
        }
    }
}
