// <auto-generated />
using System;
using System.Collections.Generic;
using ContentPilot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContentPilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908201759_BrandBrain")]
    partial class BrandBrain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentPilot.Domain.Branding.AudiencePersona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("segment");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audience_personas");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_audience_personas_brand_id");

                    b.HasIndex("TenantId", "BrandId", "IsPrimary")
                        .HasDatabaseName("ix_audience_personas_tenant_id_brand_id_is_primary");

                    b.ToTable("audience_personas", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.PrimitiveCollection<List<string>>("_languages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("languages");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_brands_tenant_id_name");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("media_type");

                    b.Property<short>("Origin")
                        .HasColumnType("smallint")
                        .HasColumnName("origin");

                    b.Property<Guid?>("ParentAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_asset_id");

                    b.Property<string>("PerceptualHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("perceptual_hash");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variant")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("variant");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.PrimitiveCollection<List<string>>("_dominantColors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("dominant_colors");

                    b.PrimitiveCollection<List<string>>("_tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_brand_assets");

                    b.HasIndex("ParentAssetId")
                        .HasDatabaseName("ix_brand_assets_parent_asset_id");

                    b.HasIndex("BrandId", "Sha256", "Variant")
                        .IsUnique()
                        .HasDatabaseName("ix_brand_assets_content");

                    b.HasIndex("TenantId", "BrandId", "Kind")
                        .HasDatabaseName("ix_brand_assets_tenant_id_brand_id_kind");

                    b.ToTable("brand_assets", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Messaging")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("messaging");

                    b.Property<string>("OperatorNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("operator_notes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Visual")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("visual");

                    b.Property<string>("Voice")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("voice");

                    b.HasKey("Id")
                        .HasName("pk_brand_profiles");

                    b.HasIndex("BrandId")
                        .IsUnique()
                        .HasDatabaseName("ix_brand_profiles_brand_id");

                    b.ToTable("brand_profiles", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandProfileVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_brand_profile_versions");

                    b.HasIndex("BrandId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_brand_profile_versions_brand_id_content_hash");

                    b.HasIndex("TenantId", "BrandId", "CreatedAt")
                        .HasDatabaseName("ix_brand_profile_versions_tenant_id_brand_id_created_at");

                    b.ToTable("brand_profile_versions", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.ContentPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<int>("CarouselsPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("carousels_per_week");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("GenerationDay")
                        .HasColumnType("smallint")
                        .HasColumnName("generation_day");

                    b.Property<TimeOnly>("GenerationTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("generation_time");

                    b.Property<int>("PostsPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("posts_per_week");

                    b.Property<int>("ReelsPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("reels_per_week");

                    b.Property<bool>("ScheduledGenerationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("scheduled_generation_enabled");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<List<string>>("_excludedTopics")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("excluded_topics");

                    b.PrimitiveCollection<List<string>>("_preferredTopics")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("preferred_topics");

                    b.PrimitiveCollection<int[]>("_publishDays")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("publish_days");

                    b.HasKey("Id")
                        .HasName("pk_content_preferences");

                    b.HasIndex("BrandId")
                        .IsUnique()
                        .HasDatabaseName("ix_content_preferences_brand_id");

                    b.HasIndex("GenerationDay")
                        .HasDatabaseName("ix_content_preferences_scheduled")
                        .HasFilter("scheduled_generation_enabled");

                    b.ToTable("content_preferences", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.IndustryProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_industry_profiles");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_industry_profiles_key");

                    b.ToTable("industry_profiles", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.ProductFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("evidence");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("key");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("statement");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_product_facts");

                    b.HasIndex("BrandId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_product_facts_brand_id_key");

                    b.ToTable("product_facts", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Limits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Infrastructure.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("locked_by");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("LeaseUntil")
                        .HasDatabaseName("ix_jobs_leased")
                        .HasFilter("state = 1");

                    b.HasIndex("RunAt", "Priority")
                        .HasDatabaseName("ix_jobs_pending")
                        .HasFilter("state = 0");

                    b.HasIndex("TenantId", "Type", "State")
                        .HasDatabaseName("ix_jobs_tenant_id_type_state");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.AudiencePersona", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audience_personas_brands_brand_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.Brand", b =>
                {
                    b.HasOne("ContentPilot.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brands_tenants_tenant_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandAsset", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_assets_brands_brand_id");

                    b.HasOne("ContentPilot.Domain.Branding.BrandAsset", null)
                        .WithMany()
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_brand_assets_brand_assets_parent_asset_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandProfile", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_profiles_brands_brand_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.BrandProfileVersion", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_profile_versions_brands_brand_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.ContentPreferences", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_preferences_brands_brand_id");
                });

            modelBuilder.Entity("ContentPilot.Domain.Branding.ProductFact", b =>
                {
                    b.HasOne("ContentPilot.Domain.Branding.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_facts_brands_brand_id");
                });
#pragma warning restore 612, 618
        }
    }
}
